export const SEARCH_FOCUSED = 'header/search_focused'
export const SEARCH_BLUR = 'header/search_blur'
export const LIST_CHANGE  = 'list_change'
export const SEARCH_ENTER = 'search_enter'
export const SEARCH_LEAVE = 'search_leave'
export const CHANGE_HOT = 'change_hot'